# Previous Abstract (308 words)
_Oreophryne_ sensu lato [@Boettger:1895] is the largest clade of the hyperdiverse microhylid frog subfamily Asterophryinae, and is of particular concern for revision. _Oreophryne_ is a large genus (75 species) with a surprisingly expansive distribution across Papua New Guinea to Southeast Asia, representing nearly all of the arboreal species in the Asterophryinae. A recent molecular phylogeny has demonstrated that Oreophryne as currently recognized is polyphyletic and consists of two reciprocally monophyletic genera, one of which is highly supported as being the most basal of the entire subfamily whereas the other unrelated genus is ~2M years younger. Our acquisition of four samples from North Maluku Island, Indonesia, including a specimen of the type species, _O. senckenbergiana_, has now allowed for a decisive resolution as to which clade can bear the name _Oreophryne_. We sequenced five loci (three nuclear: BDNF, SIA, NXC, and two mitochondrial: CytB, ND4), aligned them to the 236 tip Asterophryinae molecular dataset of @Hill:2022 and regenerated the phylogeny using Maximum Likelihood inference in IQTREE2. The type species fell into the more basal clade ["Oreophryne A" in @Hill:2022] indicating that the true _Oreophryne_ is the sister branch to the rest of Asterophryinae. All four North Maluku island specimens were closely related and formed a monophyletic clade, which diverged from sister taxa on New Guinea Island about 10 MYA. We propose the name _Auparoparo_ for the new genus [the younger clade Oreophryne B in @Hill:2022]. These genera remain morphologically similar and we provide an analysis of their morphological traits and distribution in addition to redefinition. Our findings clearly demonstrate that a second clade of primarily arboreal frogs has evolved within Asterophryne, making these two clades strong candidates for convergent evolution. More complete sampling of additional species with greater range can help to further inform the dynamics of ecological diversification.

{{< pagebreak >}}

# From Allen

We note that @Hill:2022 found _Aphantophryne pansa_ nested within "Oreophryne B." The three currently recognized species of Aphantophryne possess a unique suite of morphological features: (1) absence of clavicles and procoracoid cartilage; (2) seven presacral vertebrae; (3) digits with rounded tips lacking flattening or terminal grooves; and (4) short hind legs (Zweifel and Parker, 1989). Their relationship to Oreophryne (sensu lato) needs to be confirmed by future research.


If we are to name "Oreophryne B"  as _Auparoparo_ we have got to assume that _Aphantophryne_ is not included in "Oreophryne B." I strongly suspect that it is not. Otherwise The rules for zoological nomenclature are clear; for the same reason that Oreophryne A remains as Oreophryne (because the type species is in that clade), Oreophryne B would become Aphantophryne if it includes Aphantophryne pansa.



# Cut Aphantophryne text 1 {#sec-cut1}

Recent molecular phylogenetic reconstruction of Asterophryinae has established with strong support that _Oreophryne_ sensu lato is in fact polyphyletic, and suggest that members of the genus _Aphantophryne_ may be contained within _Oreophryne_ sensu lato [@Hill:2022;@Hill:2023]. _Aphantophryne_ is a small, fossorial genus limited to high elevation that was first described by (@Fry:1917). They lack clavicles, and have never been hypothesized as members of Oreophryne on the basis of morphology.


In addition, the hypothesis that Aphatophryne is contained within one of these clades requires confirmation. ... several species of Aphantophryne to resolve the genus Oreophryne, ..., to confirm the synonymization of Aphantophryne

# Cut Aphantophryne text 2 {#sec-cut2}
[@Fry:1917] described the genus Aphantophryne to accommodate Aphantophryne pansa, a species that he named from six specimens from the summit region of Mt. Scratchley in the Owen Stanley Mountains of what is today Papua New Guinea, that lacked a sternum, procoracoid cartilage, clavicles and digital discs. Zweifel (1956) noted on the basis of additional material that Aphantophryne pansa actually possessed a sternal plate and placed it within the genus Cophixalus, noting, however, that it differed from other species of Cophixalus in having a squat, “toad-like” form and lacked digital discs. Zweifel and Allison (1982) in describing a new ground-dwelling species of Cophixalus, C. sphagnicola, from the summit of Mt Kaindi, near Wau at the western tip of the Owen Stanley Range, re-examined the validity of Aphantophryne and left it synonymized with Cophixalus. In 1989, Zweifel and Parker described two new species of ground-dwelling montane frogs from specimens that they collected in 1987 from the central Owen Stanley Mountains, and noted that these taxa both had a squat-like appearance similar to Cophixalus pansus and also, like that species, had an overlooked skeletal feature, which differentiated all three taxa from Cophixalus and related genera in possessing seven instead of eight presacral vertebrae. Primarily on the basis of this feature, Zweifel and Parker (1989) resurrected the genus Aphantophryne, and re-diagnosed it as differing from Cophixalus and related genera in possessing seven presacral vertebrae and in addition lacking clavicles and procoracoid cartilage and having short hind legs and digits with rounded tips.

# Cut from methods

We add a second taxon of _Aphantophryne_, _A. sabini_ also in a molecular phylogeny for the first time, as well as additional samples of _Aphantophryne pansa_ from a new site.

# Cut from results - this section mentions all Oreophryne, Auparoparo, and Aphantophryne 

_Oreophryne_ sensu lato is diagnosed by characters of the pectoral girdle: posessing highly reduced, curved precoracoid cartilages and clavicles, and lacking an omosternum [@Parker:1934, @Zweifel:2003]. We found that this suite of characters are present in both _Oreophryne_ and _Auparoparo_, but not _Aphantophryne_, and therefore is not diagnostic for _Oreophryne_ nor _Auparoparo_ either separately nor for both clades together (@tbl-morph). _Aphantophryne_ in contrast, lacks clavicles as well as procoracoid cartilages and an omasternum. 


Two traits imperfectly segretate between the clades, toe disc widths and call type (@tbl-morph), which may assist in preliminary identification. _Aphantophryne_ is a small, high-elevation fosssorial clade that call using "clicks" and have no toe discs. They have undifferentiated toe tips with ordinary squamous epithelium [@Green:1986]. _Oreophryne_ is an arboreal clade with expanded digital dics of roughly equal width between the fingers and toes, whereas _Auparoparo_ excluding _Aphantophryne_ have visibly larger finger pads, with finger pads roughly 20-30% wider than toes. Both _Oreophryne_ and _Auparoparo_ excluding _Aphantophryne_ use a variety of call types, with "honks" or "peeps" used only by _Oreophryne_, whereas "whinny" calls are used only by arboreal _Auparoparo_. A minority of species in both groups use the "rattle" call type. Aside from the fact that _Aphantophryne_ and _Auparoparo_ are so phenotypically distinct that no diagnostic traits identify them as a group, both toe disc width and call type are variable traits with some overlap and thus not reliable for diagnosis. Furthermore, toe disc is clearly an adaptive trait for arboreality. 

# Cut from Auparoparo diagnosis

Researchers should be aware of a high-elevation morphotype exception that are terrestrial or fossorial species, included in subgenus nov. _Aphantophryne_, previously genus _Aphantophryne_. We suspect that there are other members in the genus that have not yet been sequenced which may exhibit specialized features that vary from those described, including smaller body size and less digital disc expansion.

We also deprecate the genus _Aphantophryne_ to a subgenus within _Auparoparo_, transferring species: _Auparoparo Aphantophryne pansa_ (Fry, 1917), _Auparoparo Aphantophryne sabini_ (Zweifel and Parker, 1989).

__Subgenus Aphantophryne (Fry 1917)__

__Diagnosis:__  These species were previously designated as the genus _Aphantophryne_ and have the following distinctive morphological traits including: (1) absence of clavicles and procoracoid; (3) loss of a sternum or presence of a vestigial sternum; (4) absence of digital discs; (5) unwebbed toes and rounded tips; (6) clicking calls (7) fossorial lifestyle.

__Content:__ _Aphantophryne_ consists of three named species, _A. pansa_, _A. sabini_, and _A. minuta_. Zweifel and Parker (1989) mentioned the species A. minuta differs from the other two in its small size and relatively smaller first finger in proportion. Currently, no sample or phylogenetic data of A. minuta was obtained and thus this species is not included in this analysis. Given that _A. pansa_ [@Fry:1917] is the type species of the genus _Aphantophryne_, we deprecate Aphantophryne to a subgenus within _Auparoparo_.

 and therefore recommend deprecation of _Aphantophryne_ to a subgenus within _Auparoparo_
 
__Comment:__ According to ICZN convention for nomenclature assignment, the presence of one _Aphantophryne pansa_ sequence grouped within _Auparoparo_ could be considered a name of priority [@ICZN:1999]. However, we suspect that _Aphantophryne_ may actually represent a highly specialized morphotypic group with members belonging to other clades, which would invalidate its generic status. Future research is needed to clarify the placement and integrity of _Aphantophryne_. Furthermore, based on the tremendous morphological and lifestyle differences between _Aphantophryne pansa_ and other species of _Auparoparo_, we do not consider this name to be representative of the entire clade.


# Cut from discussion

One might hope that this trait is at least useful for limiting specimens to these two genera, however, our phylogenetic results clearly show that this trait may lead to the exclusion of non-arboreal taxa (i.e., the fossorial "Aphantophryne").”

Fossorial, high-elevation Auparoparo (formerly Aphantophpryne) lack differentiated digit pads altogether (@Green:1986).

The phylogenetic overlay on the geographic distribution shows that the earliest split of Oreophryne ~18MYA led to subclades with a primarily westward distribution and another with a more easterly distribution. The westward subclade diversified along the mainland of New Guinea (the north coast of New Guinea, the Central Cordillera), and expanded to the the (~12 MYA) North Maluku Islands and the Southern Philippines (~5MYA). The eastward subclade overlaps along the North coast of New Guinea and the Central Cordillera, but extends throughout Southeast extent of the island to both near offshore islands (Fergusson and Normanby of the DʻEntrecasteux Islands), as well as the distant Rossel Island of the Louisiade.

The inclusion of Aphantophryne expands the range of Auparoparo north-westward to the high central mountain cordillera of Southeastern Papua New Guinea (~10 MYA, Figure 2, phylomap).

Furthermore, species geographic ranges were suggestive of segregation by character state (@Kraus:2013).


### How much ecomorph evolution is happening in these groups?

_Oreophryne_ sensu lato are generally recognized as low to mid-elevation species, with only a few known from high elevation above ~2800 m (@Zweifel:2005 characterized six species). These high-elevation Oreophryne are described as terrestrial, living in meadows or alpine grass and secretive, with shorter limbs, reduced finger and toe pads and smaller hands, and superficially resemble Aphantophryne, but possesses the cartilaginous procoracoid reaching the scapula characteristic of Oreophryne (@Zweifel:2005). The discovery of a high-elevation fossorial morphotype of Auparoparo, expands our notion of what these clades may possibly look like. We may soon discover that Oreophryne and Auparoparo are more phenotypically, ecologically, and geographically diverse than previously appreciated.

Oreophryne sensu lato are known from Western New Guinea, Sulawesi, the Lesser Sunda Islands, and other areas?? and there are also many species which are undescribed or yet to be sampled.


Our study illustrates why the recent proposal of (@Dubois:2021) synonymizing all Asterophryinae genera into one large genus-level clade would only serve to confuse our understanding of Pacific biodiversity. Although they did not find phylogenetic structure at the generic level, it is important to point out that these results were based on a supermatrix approach and are in conflict with all other recent molecular studies (@Koehler:2008; @deSa:2012; @Peloso:2016; @Rivera:2017; @Tu:2018; @Hill:2022; @Hill:2023) that found substantial phylogenetic structure among the recognized genera. Future studies must remain vigilant with regard to data quality and carefully interrogate data obtained from public databases, as it is well-known that errors in taxonomic identity of the sample are often left uncorrected, among other sources of potential error. Although it is commonly assumed that good data will swamp out the bad, in our experience this is not necessarily true. @Hill:2022 found that nodal support was sensitive to completion of the data matrix and rigorous scrutiny of data quality (i.e., strong data cleaning). These issues will only be amplified in sparse supermatrix approaches where only few data are available for many inferences, and may explain the discrepancy between studies.
Taxonomists have been working for over a hundred years to clarify the structure of this group, and the growing body of molecular phylogenetic studies has thus far confirmed the monophyly of 16 generic-level taxa.
